Section "Device"
    Identifier "LCD"
    Driver "fbdev"
    Option "fbdev" "/dev/fb1"
    Option "ShadowFB" "false"
EndSection

Section "Screen"
    Identifier "LCD Screen"
    Device "LCD"
    Monitor "LCD Monitor"
    DefaultDepth 16
    SubSection "Display"
        Depth 16
        Modes "480x320"
        Virtual 480 320
    EndSubSection
EndSection

Section "Monitor"
    Identifier "LCD Monitor"
    HorizSync 28.0-80.0
    VertRefresh 43.0-72.0
    Option "DPMS" "false"
EndSection

Section "ServerLayout"
    Identifier "LCD Layout"
    Screen "LCD Screen"
EndSection
