Section "InputClass"
    Identifier "ADS7846 Touchscreen"
    MatchProduct "ADS7846 Touchscreen"
    MatchDevicePath "/dev/input/event*"
    Driver "evdev"
    Option "Calibration" "200 3900 3900 200"
    Option "InvertY" "1"
    Option "SwapAxes" "0"
    Option "EmulateThirdButton" "0"
    Option "EmulateWheel" "0"
EndSection
